### ISSUE TITLE
Test Result pane is empty

### ISSUE THREAD

**Issue by IgorKrupenja** [vitest-dev/vscode#175] opened 2023-07-26 10:25 UTC
**Describe the bug**

VSCode Test results pane is empty.

**To Reproduce**

Steps to reproduce the behavior on [this example project](https://github.com/IgorKrupenja/blog). At the moment it has just a couple of very simple tests.

1. Open the repo above from VSCode.
2. Open Testing in Sidebar.
3. Click run tests.

**Expected behavior**

Tests are run and you can see output in Test Result pane. 

Instead, tests are run correctly but the pane is empty, see screenshot below. Everything else works fine.

**Screenshots**

![image](https://github.com/vitest-dev/vscode/assets/26354715/5de23f01-d036-4d1c-a8e9-484acba56365)

**Environment**

(Paste info.txt content generated by [the example project](https://github.com/zxch3n/vitest-ext-basic-example))

- OS: macOS 13.4.1 (c)
- VSCode version:  1.80.1
- Vitest version: 0.33.0
- Vitest plugin version: v0.2.42

**Comment by daniel-johns-99** [comment] 2024-01-03 13:56
Anyone else found a workaround/fix for this?

**Comment by mikechu-optimizely** [comment] 2024-01-05 19:47
This happens to me too. I saw it for a split moment before it's cleared. I was hoping to click on the right-hand list of runs and see individual results. 

I'll go back to my running the tests in the Terminal windows, so I can read the output.

**Comment by lsaadeh** [comment] 2024-01-11 01:37
having this issue and I don't use vitest-dev but jest

**Comment by htndev** [comment] 2024-01-15 12:38
The same issue to me.
![image](https://github.com/vitest-dev/vscode/assets/29665511/90aef721-fac2-4006-b3ce-885ee207b304)

**Comment by Otoris** [comment] 2024-01-29 21:19
+1 same issue

**Comment by oenu** [comment] 2024-02-01 18:44
Issue Persists

**Comment by olgashev** [comment] 2024-02-02 16:04
+1. The issue persists for quite a long period. I never saw it not clean after a test was executed. Instead, I have a new terminal with Jest results, opened in the terminals list.

**Comment by deeepwin** [comment] 2024-02-04 09:05
> Have same issue since quite some time, is there a work around?

Fixes it for me: 

"python.testing.pytestArgs": [
    "-s"
],

**Comment by simonalbrecht** [comment] 2024-02-13 07:26
For me setting the `Output Config` to `terminal-based` made the output show up. Not sure why the default doesn't. 

See https://github.com/jest-community/vscode-jest?tab=readme-ov-file#outputconfig

**Comment by sheremet-va** [comment] 2024-03-15 18:00
I am not sure what is expected in "Test Results" panel. The same thing that Vitest outputs?

**Comment by sheremet-va** [comment] 2024-04-03 17:33
Pre-release version of Vitest extension only prints user's logs in "Test Result" panel. This is by design - we decided to not replicate the same output from Vitest terminal because you can already see same results in Visual Studio Code interface, and it's actually more interactive. This also makes the extension a bit faster because we don't need to spend time to format the output.

If there is a strong reason to display the same output that Vitest does in the terminal, feel free to leave a comment. But I am closing this issue for now.

**Closed by sheremet-va** 2024-04-03 17:33 UTC
Labels: p2-nice-to-have
