### ISSUE TITLE
snapshotUpdate property is always "new" when updating snapshots via the "Update snapshot" option

### ISSUE THREAD

**Issue by ffMathy** [vitest-dev/vscode#527] opened 2024-11-12 10:58 UTC
### Describe the bug

snapshotUpdate property is always "new" when updating snapshots via the "Update snapshot" option in the VS Code extension.

It is correctly reflected when I am using Vitest from the console.

See my repro where I am trying to inject the property in. That's what is giving the wrong output.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-get8mf?file=test%2Fglobal-setup.ts

It does not happen when running Vitest from the CLI.

```vitest --update``` correctly shows "updateMode" as "all"

```vitest``` correctly shows "updateMode" as "new"

But when running from VS Code, even if I right click on a test and click "Update snapshot", "updateMode" is "new". I expected it to be "all" here.

### Output

```shell
[10:56:00 AM] Initiating deferred test run
[INFO 10:56:00 AM] Running 1 file(s) with name pattern: ^\s?JSON$
[10:56:00 AM] The runner is starting because tests test/basic.test.ts were started due to a file change
[10:56:00 AM] Enqueuing "JSON"
[10:56:00 AM] No task result for "test/basic.test.ts", ignoring
[10:56:00 AM] Enqueuing "JSON" because it was just collected
[10:56:00 AM] No errors found for "test/basic.test.ts"
[10:56:00 AM] Marking "JSON" as running
[10:56:10 AM] Marking "JSON" as passed
[10:56:10 AM] No errors found for "test/basic.test.ts"
[10:56:10 AM] Ending test run test/basic.test.ts
[10:56:10 AM] [VSCODE] Ignoring file: node_modules/.vitest/vitest/results.json
```

### Version

v1.6.6

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ffMathy** [comment] 2024-11-25 10:46
@sheremet-va this one would be great to have fixed (or at least triaged). We rely on this heavily today.

**Comment by sheremet-va** [comment] 2024-11-25 16:02
Next Vitest minor will provide the actual `project` instance and you will be able to reference serialized config: https://github.com/vitest-dev/vitest/pull/6942

For now, I am closing this because the error can be reproduced on Vitest side during the watch mode and it's not specific to the vscode extension.

**Comment by ffMathy** [comment] 2024-11-28 11:52
Hmmm I still see no `project` property on the context provided in the global setup. I have vitest `2.1.6`.

**Comment by ffMathy** [comment] 2024-12-02 13:46
Ah, I missed the docs. But I still don't see the value updated.

Here's what I am doing in my global setup:

```typescript
  const vitest = await createVitest('test', {});

  const project = vitest.projects[0];
  if (!project) {
    throw new Error('No project found');
  }

  console.log(project.config.snapshotOptions.updateSnapshot); //now this is always "new", even if running from the console
```

**Comment by ffMathy** [comment] 2024-12-02 13:54
I also tried using `project.getSerializableConfig()`, but that just still has an `updateSnapshot` property with the value "new".

Sorry, I am missing how I should fetch this information? The given documentation doesn't help me much.

**Comment by hi-ogawa** [comment] 2024-12-03 00:30
This feature will be available from 2.2, so it's only on beta release right now https://main.vitest.dev/advanced/api.html#testproject

On beta, what you can do is something like this https://stackblitz.com/edit/vitest-dev-vitest-get8mf?file=test%2Fglobal-setup.ts

```ts
import type { SnapshotUpdateState } from 'vitest';
import type { TestProject } from 'vitest/node';

export default function setup(ctx: TestProject) {
  ctx.provide(
    'config:updateSnapshot',
    ctx.serializedConfig.snapshotOptions.updateSnapshot
  );
  ctx.onTestsRerun(() => {
    ctx.provide(
      'config:updateSnapshot',
      ctx.serializedConfig.snapshotOptions.updateSnapshot
    );
  });
}

declare module 'vitest' {
  export interface ProvidedContext {
    'config:updateSnapshot': SnapshotUpdateState;
  }
}
```

**Comment by ffMathy** [comment] 2024-12-03 04:16
Aha, I see! Thanks for providing such a great example. Much appreciated!

Any ETA on the release of 2.2?

**Comment by sheremet-va** [comment] 2024-12-03 08:42
> Any ETA on the release of 2.2?

January

**Comment by ffMathy** [comment] 2024-12-04 00:11
Thanks. Happy holidays and great work! 😍

**Closed** 2024-12-09 09:58 UTC
Labels: pending triage
