### ISSUE TITLE
Iterative tests break when run directly from plugin

### ISSUE THREAD

**Issue by roydukkey** [vitest-dev/vscode#130] opened 2023-02-02 20:57 UTC
**Describe the bug**
Tests as describe on this issue https://github.com/vitest-dev/vitest/issues/794 fail with:

```
TypeError: Cannot read properties of undefined (reading 'children')
```

**To Reproduce**
```js
[1, 2, 0].forEach((num) => {
	it(`${num} is a number (foreach)`, () => {
		expect(typeof num).toEqual('number');
	});
});
```

**Screenshots**
![Screenshot 2023-02-02 at 15 54 08](https://user-images.githubusercontent.com/1509616/216447122-521f2e88-a7a8-405a-8667-fe20231e0154.png)

**Environment**

- OS: macOS
- VSCode version: 1.74.3 (Universal)
   - Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
   - Date: 2023-01-09T17:07:18.579Z (3 wks ago)
   - Electron: 19.1.8
   - Chromium: 102.0.5005.167
   - Node.js: 16.14.2
   - V8: 10.2.154.15-electron.0
   - OS: Darwin arm64 22.2.0
   - Sandboxed: No
- Vitest version: 0.28.3
- Vitest plugin version: 0.2.37

**Comment by zxch3n** [comment] 2023-02-09 03:15
Duplicate of #7

**Closed by zxch3n** 2023-02-09 03:15 UTC
Labels: bug, duplicate
