### ISSUE TITLE
Can´t modify directory tree

### ISSUE THREAD

**Issue by dvegap** [vitest-dev/vscode#420] opened 2024-06-19 05:16 UTC
Type: <b>Bug</b>

When running the extension, trying to modify the directory tree wherever but it´s leaves result on a permission error. I guess it must be running a watcher or something, which is unexpected, since tests only run on demand and there seems to be no configuration in the docs to modify this behavior

Extension version: 0.12.3
VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700HX (24 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.65GB (6.11GB free)|
|Process Argv|--crash-reporter-id 74541171-8bcc-4e8b-979e-b03ef26e213e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideot:31016892
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31077528

```

</details>

**Comment by tkfmed** [comment] 2024-06-21 05:31
I have similar problem. On addition, I can't reinstall node packages (npm ci) when the extension is turned on. When I stop the vitest process, things works fine.

**Comment by sheremet-va** [comment] 2024-10-08 09:28
Duplicate of #418

**Closed by sheremet-va** 2024-10-08 09:28 UTC
