### ISSUE TITLE
Support custom `dir` from vitest config

### ISSUE THREAD

**Issue by Exelord** [vitest-dev/vscode#123] opened 2023-01-19 20:07 UTC
**Is your feature request related to a problem? Please describe.**
Im using vitest together with playwright and I keep both tests suites in different folders. I have used vitest config property `dir` to customize a base path where tests are located, however the vscode extension seams to not respect that.

**Describe the solution you'd like**
Respect config property.

**Describe alternatives you've considered**
Seams no other option.

**Comment by sandercoffee** [comment] 2023-02-07 09:54
current extension doesn't work with turborepo :(

**Comment by Exelord** [comment] 2023-02-07 12:04
I am not using turborepo :)

**Comment by zxch3n** [comment] 2023-02-09 03:10
Duplicate of #101

**Comment by Exelord** [comment] 2023-02-09 11:14
I don't thing this is related. I don't have a problem with running tests. Instead it's about vitest config that is not respected.

**Comment by sheremet-va** [comment] 2024-03-15 18:13
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.

**Closed by sheremet-va** 2024-03-15 18:13 UTC
Labels: duplicate, p2-nice-to-have, feat: workspace
