### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by searene** [vitest-dev/vscode#44] opened 2022-05-31 12:02 UTC
**Describe the bug**
Maybe I didn't use the addon in the correct way? But simply put, the addon is not working at all. After installing it, I saw the testing tab, I saw the little error beside the test, but no matter where I click, the test is not running.

**To Reproduce**
1. Git clone this repository: `https://github.com/zxch3n/vitest-ext-basic-example`
2. Run `node setup.mjs`.
3. Open it with VSCode.
4. Click on the arrow beside the test to start testing. Nothing happens.

**Expected behavior**
It should start testing.

**Screenshots**
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/3351317/171168582-d8bb093b-b29c-4746-9071-01e10a043415.png">

**Environment**

```json
{
  "System": {
    "OS": "macOS 12.4"
  },
  "Binaries": {
    "Node": {
      "version": "18.2.0",
      "path": "~/.nvm/versions/node/v18.2.0/bin/node"
    },
    "Yarn": {
      "version": "1.22.18",
      "path": "/usr/local/bin/yarn"
    },
    "npm": {
      "version": "8.9.0",
      "path": "~/.nvm/versions/node/v18.2.0/bin/npm"
    }
  },
  "IDEs": {
    "VSCode": {
      "version": "1.67.2",
      "path": "/usr/local/bin/code"
    }
  },
  "npmPackages": {
    "vite": {
      "installed": "2.9.9",
      "wanted": "^2.9.9"
    },
    "vitest": {
      "installed": "0.12.10",
      "wanted": "^0.12.6"
    }
  }
}
```

**Comment by fauxparse** [comment] 2022-06-03 03:28
+1

**Comment by emanuelarcos** [comment] 2022-06-17 18:32
+1

**Comment by zxch3n** [comment] 2022-06-18 07:34
Could you switch to the pre-release version and check whether it acts the same? If so, please attach the output log from Vitest to help me locate the issue.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/18425020/174427675-844ba05d-5ba6-4fff-b825-5e251d2667b3.png">

I'm also using macOS, but I cannot reproduce this error. I need you guys' help, thanks.

**Comment by searene** [comment] 2022-06-19 06:10
@zxch3n

Hi, how to switch to the pre-release version? Are there any guidelines?

**Comment by zxch3n** [comment] 2022-06-19 06:14
@searene You can do it in the extension homepage 
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/18425020/174468318-435a1827-f3ca-410e-a576-128287af01cd.png">

**Comment by searene** [comment] 2022-06-20 12:58
@zxch3n Hi,

After I started the `1 + 1 = 2` test by clicking here using the pre-release version

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/3351317/174606218-c9ca7447-a36e-4f91-8c49-206d4cf947c6.png">

I got the following output:

```
[INFO 8:53:41 PM] Vitest Workspace [vitest-ext-basic-example]: Vitest version = 0.12.10
[INFO 8:55:01 PM] Tests run start
[INFO 8:55:01 PM] [Workspace "vitest-ext-basic-example] Run tests from workspace
[INFO 8:55:01 PM] [Execute Vitest] ./node_modules/.bin/vitest /Users/joey/WebstormProjects/vitest-ext-basic-example/add.test.ts -t add 1 + 1
[INFO 8:55:01 PM] Start api process at port 65185
[INFO 8:55:01 PM] [RUN] ./node_modules/.bin/vitest /Users/joey/WebstormProjects/vitest-ext-basic-example/add.test.ts -t add 1 + 1
[INFO 8:55:01 PM] [RUN.cwd] /Users/joey/WebstormProjects/vitest-ext-basic-example
[INFO 8:55:01 PM] WS Close
[INFO 8:55:01 PM] WS Close
[INFO 8:55:01 PM] WS Close
[INFO 8:55:02 PM] WS Close
[INFO 8:55:02 PM] WS Close
[INFO 8:55:02 PM] WS Opened
[INFO 8:55:02 PM] WS Opened
[INFO 8:55:02 PM] 

 DEV  v0.12.10 /Users/joey/WebstormProjects/vitest-ext-basic-example

      API started at http://localhost:65185



[INFO 8:55:03 PM] Vitest api process finished
[INFO 8:55:03 PM] [Workspace "vitest-ext-basic-example] Test run finished
[INFO 8:55:03 PM] Tests run end
[INFO 8:55:03 PM] WS Close
[INFO 8:55:03 PM] WS Close
[INFO 8:55:03 PM] API PROCESS EXIT
[INFO 8:55:03 PM] Vitest api process finished
[Error 8:55:03 PM] 
Failed to get any result
( Vitest should be configured to be able to run from project root )

Error when running
    ./node_modules/.bin/vitest /Users/joey/WebstormProjects/vitest-ext-basic-example/add.test.ts -t add 1 + 1

cwd: /Users/joey/WebstormProjects/vitest-ext-basic-example
node: v18.2.0

env.PATH: /Users/joey/.nvm/versions/node/v18.2.0/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/joey/.cargo/bin:/Users/joey/apps/fd:/Users/joey/.emacs.d/bin

[Error 8:55:03 PM] 

 DEV  v0.12.10 /Users/joey/WebstormProjects/vitest-ext-basic-example

      API started at http://localhost:65185



[INFO 8:55:03 PM]  ↓ add.test.ts  (1 test | 1 skipped)



Test Files  1 skipped (1)

     Tests  1 skipped (1)

      Time  909ms (in thread 0ms, Infinity%)





 PASS  Waiting for file changes...

       press h to show help, press q to quit
```

Seems like the test is skipped. By the way, when I ran the test manually outside of VSCode using the following command:

```sh
./node_modules/.bin/vitest /Users/joey/WebstormProjects/vitest-ext-basic-example/add.test.ts -t add 1 + 1
```

The test is passed as expected:

```
 DEV  v0.12.10 /Users/joey/WebstormProjects/vitest-ext-basic-example

 √ add.test.ts (1)

Test Files  1 passed (1)
     Tests  1 passed (1)
      Time  796ms (in thread 2ms, 39794.48%)


 PASS  Waiting for file changes...
       press h to show help, press q to quit
```

**Comment by benbender** [comment] 2022-07-21 06:59
Same problem on m1-osx with a solid-project :/

**Comment by benblazak** [comment] 2022-08-05 04:26
Works for me, following the steps to reproduce on an M1 Mac Mini, using the pre-release version of the plugin. Node 18.4.0 (and npm, not yarn, if that makes a difference).

I am having problems getting it to work in a svelte project (even a newly initialized one) though.

**Comment by niktek** [comment] 2022-08-11 05:05
m1 Mac, svelte-kit project, it can see all the tests, but can't run them:
```
[INFO 3:01:36 pm] Tests run start
[INFO 3:01:36 pm] [Workspace "dev-skeleton] Run tests from workspace
[INFO 3:01:36 pm] [Execute Vitest] vitest /Users/nik/code/github/dev-skeleton/src/lib/Accordion/AccordionGroup.test.ts -t Accordion.svelte Renders without props
[INFO 3:01:36 pm] Start api process at port 55986
[INFO 3:01:36 pm] [RUN] vitest /Users/nik/code/github/dev-skeleton/src/lib/Accordion/AccordionGroup.test.ts -t Accordion.svelte Renders without props
[INFO 3:01:36 pm] [RUN.cwd] /Users/nik/code/github/dev-skeleton
[INFO 3:01:36 pm] WS Close
[INFO 3:01:37 pm] WS Close
[INFO 3:01:37 pm] WS Close
[INFO 3:01:37 pm] WS Close
[INFO 3:01:37 pm] WS Close
```

`pnpm test` runs the tests in the console fine.

**Comment by zachequi** [comment] 2022-08-29 18:04
Same issue for me on linux, it looks like the websocket never connects (no WS Open message).  I can confirm downgrading `vitest` works.  Using latest vitest 0.22.1 and extension 0.2.28

**Comment by ahoyahoy** [comment] 2022-11-05 05:40
version 0.2.15 works for me as the last one
win 10

**Comment by zxch3n** [comment] 2023-02-09 04:00
This issue should be fixed now. If it's still wrong, let me know

**Closed by zxch3n** 2023-02-09 04:00 UTC
Labels: bug
