### ISSUE TITLE
Tests not runnable on Linux

### ISSUE THREAD

**Issue by derekwsgray** [vitest-dev/vscode#31] opened 2022-05-10 21:19 UTC
**Describe the bug**
While the extension will install, it does not activate automatically. Forcing it to turn on in the settings does not resolve it. 

**To Reproduce**
1. Install the extension
2. Go to the "Testing" panel - note there are no controls to run tests (not enabled)
3. Go to the extensions settings page, check the first checkbox to force enable it.
4. Observe the green triangles appear, but they do not execute any tests.

**Expected behavior**
The extension should auto-detect vitest and enable itself. Clicking the green triangles should run tests.

**Screenshots**
![image](https://user-images.githubusercontent.com/5737686/167723468-15816ff4-1427-4d6c-8ee9-71dfb24211a8.png)

**Environment**
 - OS: Linux Mint 19.3 (Ubuntu-based)
 - VSCode version: 1.67.1
 - Vitest version: 0.10.1
- Vitest plugin version: 0.1.27

**Additional context**
Following up on thread started on Discord. Tried one or two attempted fixes published but the issue remains.
Tried building/testing this repo itself and the same error occurs.

**Comment by md1440** [comment] 2022-05-16 16:38
Experiencing a similar issue on Fedora..

- Test Explorer Panel does not appear in UI
- manually enabling the plugin via `"vitest.enable": true` has not effect
- vitest runs as expected via pnpm test..


Environment

OS: Fedora 36
VSCode version: 1.67.1
Vitest version: 0.12.6
Vitest plugin version: 0.2.2

**Comment by zxch3n** [comment] 2022-05-17 12:51
@md1440 @derekwsgray can you reproduce the issue in this project? https://github.com/zxch3n/vitest-ext-basic-example

**Comment by md1440** [comment] 2022-05-17 21:22
@zxch3n 

I cloned your test project and the vitest plugins loads, running tests with the plugin fails but succeeds when ran via cli. It throws the following errors in dev tools:

`  ERR [Extension Host]  ERROR   ERROR  Unknown options: 'outputFile', 'run' - For help, run: pnpm help test`

`console.ts:137 [Extension Host]  ERROR   ERROR  Unknown options: 'outputFile', 'run'For help, run: pnpm help test`

`  ERR [Extension Host] Error: 
( Vitest should be configured to be able to run from project root )

Error when running
    pnpm test /home/marc/vitest-ext-basic-example/add.test.ts --reporter=json --reporter=verbose --outputFile /tmp/vitest-report-jwd25.json --run

cwd: /home/marc/vitest-ext-basic-example
node: v17.8.0

env.PATH: 

------

Log:
 ERROR   ERROR  Unknown options: 'outputFile', 'run'`

For help, run: pnpm help test`

    at x (/home/marc/.vscode/extensions/zixuanchen.vitest-explorer-0.2.3/dist/extension.js:35:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Lr.scheduleRun (/home/marc/.vscode/extensions/zixuanchen.vitest-explorer-0.2.3/dist/extension.js:25:94)
    at Ec (/home/marc/.vscode/extensions/zixuanchen.vitest-explorer-0.2.3/dist/extension.js:44:4381)
    at py (/home/marc/.vscode/extensions/zixuanchen.vitest-explorer-0.2.3/dist/extension.js:44:2984)
    at o.$runControllerTests (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:227589)`

When trying with my project where the issue first occured, vitest plguin doesn't start at all, it's not showing in Developer Running Extensions and it shows no Err in Dev tools. Activating it manually via settings.json has seemingly no effect, it doesn't seem to start at all.

Hope this helps. Let me know if you'd need more assist with testing...

**Comment by md1440** [comment] 2022-05-17 21:33
Addendum:

When toggling Vitest Watch Mode via command palette all works fine in your test project. When attempting the same in my project it throws:

`Command'Vitest: Toggle Watch Mode` resulted in an error (command 'vitest.toggleWatching' not found.

**Comment by zxch3n** [comment] 2022-05-18 01:31
@md1440 What does your `script.test` look like in package.json?

**Comment by md1440** [comment] 2022-05-18 19:24
In script.test I only call "test": "vitest"..  I have update to the pre-release version and it's throwing the following error in 3 test setups including your cloned sample project which actually did run fine yesterday. .bin/vtest is present in all projects:

`Error: 
( Vitest should be configured to be able to run from project root )

Error when running
    pnpm test /home/marc/vitest-ext-basic-example/add.test.ts --reporter=json --reporter=verbose --outputFile /tmp/vitest-report-5vt91.json --run

cwd: /home/marc/vitest-ext-basic-example
node: v17.8.0

env.PATH: /home/marc/.nvm/versions/node/v17.8.0/bin:/home/marc/.zplug/repos/zplug/zplug/bin:/home/marc/.zplug/bin:./bin:/usr/local/bin:/usr/local/sbin:/home/marc/.dotfiles/bin:~/.local/bin:/home/marc/.nvm/versions/node/v17.8.0/bin:/home/marc/.cargo/bin:/bin:/home/marc/.local/share/gem/ruby/bin:~/.cargo/bin:/home/marc/.yarn/bin:/home/marc/.go/bin


------

Log:
 ERROR   ERROR  Unknown options: 'outputFile', 'run'

For help, run: pnpm help test`

Strange things are happening...

**Comment by md1440** [comment] 2022-05-18 19:24
In script.test I only call "test": "vitest"..  I have update to the pre-release version and it's throwing the following error in 3 test setups including your cloned sample project which actually did run fine yesterday. .bin/vtest is present in all projects:

`Error: 
( Vitest should be configured to be able to run from project root )

Error when running
    pnpm test /home/marc/vitest-ext-basic-example/add.test.ts --reporter=json --reporter=verbose --outputFile /tmp/vitest-report-5vt91.json --run

cwd: /home/marc/vitest-ext-basic-example
node: v17.8.0

env.PATH: /home/marc/.nvm/versions/node/v17.8.0/bin:/home/marc/.zplug/repos/zplug/zplug/bin:/home/marc/.zplug/bin:./bin:/usr/local/bin:/usr/local/sbin:/home/marc/.dotfiles/bin:~/.local/bin:/home/marc/.nvm/versions/node/v17.8.0/bin:/home/marc/.cargo/bin:/bin:/home/marc/.local/share/gem/ruby/bin:~/.cargo/bin:/home/marc/.yarn/bin:/home/marc/.go/bin


------

Log:
 ERROR   ERROR  Unknown options: 'outputFile', 'run'

For help, run: pnpm help test`

Strange things are happening...

**Comment by zxch3n** [comment] 2022-05-18 22:50
@derekwsgray What is your `vitest.commandLine` setting? Can you try the pre-release version?

**Comment by md1440** [comment] 2022-05-19 08:34
Yay! Thank you @zxch3n, that seems to have been the issue for me. Setting the vitest.commandLine to `pnpm test --` instead of `pnpm test` with the pre-release version resulted in everything working as supposed across all 3 test projects :) Appreciate your help and work!

**Comment by sujeet-agrahari** [comment] 2022-05-19 19:42
Experience the same issue on MacOS with latetst VSCode version, also tried toggle command it says command does not exist.

1. No UI in explorer.
2. No effect of any vscode json setting for this extension.

**Comment by zxch3n** [comment] 2022-05-20 05:14
@sujeet-agrahari Can you try reproducing the issue on https://github.com/zxch3n/vitest-ext-basic-example/?

**Comment by sujeet-agrahari** [comment] 2022-05-20 18:01
@zxch3n It worked. Clone and ran that command. Thanks.

**Comment by derekwsgray** [comment] 2022-05-24 02:24
> @derekwsgray What is your `vitest.commandLine` setting? Can you try the pre-release version?

It's empty. I wasn't aware I was supposed to fill that in. However, entering `./node_modules/.bin/vitest` didn't improve the situation.

**Comment by zxch3n** [comment] 2022-05-24 02:36
@derekwsgray Normally you don't need to fill in that, I thought there might be some misconfigure which would have caused your problem. I made some changes and add a script in https://github.com/zxch3n/vitest-ext-basic-example. Can you try that again?

**Comment by derekwsgray** [comment] 2022-05-24 02:40
```
Error: 

( Vitest should be configured to be able to run from project root )

Error when running

    ./node_modules/.bin/vitest /home/dgray/dev/git/vitest-ext-basic-example/add.test.ts --reporter=json --reporter=verbose --outputFile /tmp/vitest-report-nwg1.json --run -t add

cwd: /home/dgray/dev/git/vitest-ext-basic-example

node: undefined
```

**Comment by derekwsgray** [comment] 2022-05-24 02:42
```json
{
  "System": {
    "OS": "Linux 5.4 Linux Mint 19.3 (Tricia)"
  },
  "Binaries": {
    "Node": {
      "version": "16.13.2",
      "path": "~/.nvm/versions/node/v16.13.2/bin/node"
    },
    "Yarn": {
      "version": "1.22.18",
      "path": "~/.yarn/bin/yarn"
    },
    "npm": {
      "version": "8.1.2",
      "path": "~/.nvm/versions/node/v16.13.2/bin/npm"
    }
  },
  "IDEs": {
    "VSCode": {
      "version": "1.67.2",
      "path": "/usr/bin/code"
    }
  },
  "npmPackages": {
    "vite": {
      "installed": "2.9.9",
      "wanted": "^2.9.9"
    },
    "vitest": {
      "installed": "0.12.9",
      "wanted": "^0.12.6"
    }
  }
}
```

**Comment by zxch3n** [comment] 2022-05-24 02:57
Seems like the cause is that the spawned process cannot find node. Is `vitest.nodeEnv` set in  https://github.com/zxch3n/vitest-ext-basic-example under .vscode/settings.json? If not, can you try setting it as `{"PATH": "~/.nvm/versions/node/v16.13.2/bin"}`

**Comment by derekwsgray** [comment] 2022-05-24 03:15
Yes, it's set and already contains that path within it.

**Comment by zxch3n** [comment] 2022-05-24 08:47
@derekwsgray You restart VS Code after settings changes, right? Sorry, I don't have clues why this is happening on your machine, and I failed to reproduce this issue in all my environments.

**Comment by derekwsgray** [comment] 2022-05-24 16:49
Yes, was restarting.

**Comment by derekwsgray** [comment] 2022-05-24 22:20
Was node installed via `nvm` in your environment?

**Comment by zxch3n** [comment] 2022-05-25 03:56
Yes, I use nvm in all my machines

**Comment by ngirardin** [comment] 2023-01-23 09:26
This looks like a duplicate of #88

**Comment by zxch3n** [comment] 2023-02-09 03:26
close as #125 merged

**Closed by zxch3n** 2023-02-09 03:26 UTC
Labels: bug, help wanted
