### ISSUE TITLE
Vitest not starting up due to failed version check on windows

### ISSUE THREAD

**Issue by DetachHead** [vitest-dev/vscode#170] opened 2023-07-10 07:17 UTC
re-raising #88 because it was closed but the issue is still occurring for many people (myself included):

> **Describe the bug** Hi there, Every time I start up vscode it keeps telling me, "Because Vitest version < 0.12.0 for every workspace folder, run/debug/watch tests from Vitest extension disabled."
> 
> Tried uninstall / install but it won't come up again.
> 
> Sth. I should be aware off ?
> 
> Thx!
> 
> **To Reproduce** have vitest 0.23.4 installed, used the cmd: npm init vue@3 to create a totally new package
> 
> installed your vitest extension.
> 
> Restart vscode, see error appearing.
> 
> **Expected behavior** possible to start the tests through test explorer or using the green play icon
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![image](https://user-images.githubusercontent.com/8349637/193000928-49592e10-6625-41b5-8d4e-c554fb2344a6.png)
> 
> **Environment** windows 10, vscode : Version: 1.71.2 (user setup) Commit: 74b1f979648cc44d385a2286793c226e611f59e7 Datum: 2022-09-14T21:03:37.738Z Electron: 19.0.12 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 Betriebssystem: Windows_NT x64 10.0.19044 Sandkasten: No
> 
>     * OS: [e.g. macOS]
> 
>     * VSCode version:
> 
>     * Vitest version:
> 
>     * Vitest plugin version:
> 
> 
> **Additional context** same setup on macos works

**Comment by suerta-git** [comment] 2023-07-29 14:18
mac os +1

**Comment by suerta-git** [comment] 2023-07-29 14:18
any workaround?

**Comment by riuandg5** [comment] 2023-08-07 13:45
I was also facing the same issue of **"not detecting vitest version correctly from vitest vscode extension upon opening of the workspace"**. However, there was no problem when I installed the extension for the first time while setting up my project in the workspace.

**Recently I tried adding `"vitest.enable": true` and `"vitest.commandLine": "npx vitest"` in vscode workspace settings and boom! it is working fine now.**

**Comment by slabinfo** [comment] 2023-08-21 07:39
I can confirm it on Linux, too.
It seems, reading from the logs, that the extension is using a wrong execution command:
[INFO 9:22:38 AM] Trying to get vitest version from /home/my/software/vscode/VSCode-linux-x64/code-insiders /home/my/dev/node_modules/.bin/vitest -v...
[INFO 9:22:38 AM] Error: Cannot get vitest version. Please open an issue at https://github.com/vitest-dev/vscode/issues and join the logs above. 

Is it trying to run vitest -v through vscode?

**Comment by callmeberzerker** [comment] 2023-10-23 18:37
It started happening  both on my windows and mac machines. Any insight on why?

**Comment by shalott** [comment] 2023-11-07 22:02
This is occurring for me on Mac as well, creating a brand new sveltekit app using Typescript, eslint, prettier, playwrite, and vitest.  It seems to be an issue specifically with pnpm. 

This command works fine and creates a project where vscode works fine: 
`npm create svelte@latest vitest_clean`

This command produces the vitest version < 0.12.0 error as seen in screenshot below:
`pnpm create svelte@latest vitest_pnpm` 

![Screenshot 2023-11-07 at 4 59 08 PM](https://github.com/vitest-dev/vscode/assets/415001/14de8f22-9598-4d18-a44e-c7b6023f86a5)

**Comment by callmeberzerker** [comment] 2023-11-08 12:20
This somehow fixed itself on my end. Didn't do anything specifically!

**Comment by callmeberzerker** [comment] 2023-11-11 19:35
This is interesting, it comes and goes - and I don't know due to what.

**Comment by zakaoai** [comment] 2023-11-30 18:25
Hello there, I finally want to try the new Yarn with PnP and seem to break a lot of vscode plugin.
Got : 
`Vitest Workspace [project]: Vitest version = undefined`

**Comment by mzietlow** [comment] 2023-12-08 09:23
For me this was caused by a blank space in the path to my project.

After switching from `C:\The Path\To My\Project` to `C:\The_Path\To_My\Project` the vitest plugin was loading correctly again.

While this workaround might work, this is still a big issue since changing the path might not always be as painless as it was in my case.

**Comment by zakaoai** [comment] 2023-12-08 09:50
> In my particular case, this was caused by a blank space in the path to my project.
> 
> After switching from `C:\The Path\To My\Project` to `C:\The_Path\To_My\Project` the vitest plugin was loading correctly again. (Just saw that this was also one of the workarounds mentioned in #88.)
> 
> While this workaround might work for me, this is still a big issue since changing the path might not always be as painless as it was in my case.

Interesting but not my problem since I dont have any blank space in my project path

**Comment by mzietlow** [comment] 2023-12-08 15:17
I'll create a new issue then

**Comment by Sebaestschjin** [comment] 2023-12-20 08:00
I'm on Windows changing the `PATH` settings, helped.

I have an environment variable `%NODE_HOME%` that points to the node installation and the `PATH` variable contains this (e.g. `%NODE_HOME%';%JAVA_HOME%/bin;%M2_HOME%/bin`). I can start `node` from the command line/Git Bash/Powershell this way. But executing the `vitest.cmd` file in `node_modules/.bin` (which is what the extension also tries to do), gives the error that `node` can not be found. Removing the `%NODE_HOME%` varialbe from `PATH` and adding the path to node directly, fixes this problem and the `vitest.cmd` can be executed and the plugin also detects the vitest version.

So the issue seems to be `vitest` itself (or the `.cmd` file it creates), which seems to handle variables in the `PATH` variable incorrectly or something.

**Comment by linzhe141** [comment] 2024-02-29 01:56
It may have something to do with the node version. After executing `nvm use 18`, reload vscode will work normally.

**Comment by sheremet-va** [comment] 2024-03-15 17:39
This should be fixed in pre-release 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.

**Closed by sheremet-va** 2024-03-15 17:39 UTC
Labels: p3-minor-bug
