### ISSUE TITLE
Vitest version not detected

### ISSUE THREAD

**Issue by asbermudez** [vitest-dev/vscode#124] opened 2023-01-20 15:55 UTC
**Describe the bug**
After latest update (0.2.37) the extension does not allow to run tests because it does not detect the Vitest version on the workspace.
The package.json and node_modules folder are in the root of the open workspace.

**To Reproduce**
Steps to reproduce the behavior on [the example project](https://github.com/zxch3n/vitest-ext-basic-example):

1. Install latest version 0.2.37 of the extension
2. Immediately get the popup that version is under 0.12.0

**Expected behavior**
The extension should detect correctly the workspace version

**Screenshots**
Message
![image](https://user-images.githubusercontent.com/46224115/213727300-e1f2fb37-d51b-4231-936e-3f82a28a9639.png)

Version and console output
![image](https://user-images.githubusercontent.com/46224115/213727139-dd03fac6-a464-4f61-b51b-e86b9057e0bb.png)

Folder structure of workspace
![image](https://user-images.githubusercontent.com/46224115/213726928-523902a4-b678-43bb-86e7-29cfe1d86fc3.png)

**Environment**
- OS: Windows 11
- VSCode version: 1.74.2
- Vitest version: 0.27.0
- Vitest plugin version: 0.2.37

**Comment by ffxsam** [comment] 2023-01-20 21:30
Experiencing this as well.

**Comment by JAKimball** [comment] 2023-01-21 01:07
This is a duplicate of #88.

**Comment by segevfiner** [comment] 2023-01-22 08:10
I'm hitting this on macOS with pnpm

**Comment by segevfiner** [comment] 2023-01-22 08:17
It works with Vitest plugin 0.2.36

**Comment by ngirardin** [comment] 2023-01-22 15:26
@asbermudez this was probably broken by https://github.com/vitest-dev/vscode/pull/118.

Could you please try the steps at https://github.com/vitest-dev/vscode/issues/88#issuecomment-1399518132 and post your results there?

**Closed** 2023-01-23 10:05 UTC
Labels: bug

**Comment by ngirardin** [comment] 2023-01-23 10:37
You're welcome 😄
